// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkH_AwO0MH6CyMYGjaVZS19NrqlK2iDes',
    appId: '1:794780865383:web:0023c40bbcc571825a15c2',
    messagingSenderId: '794780865383',
    projectId: 'pratikumshinta',
    authDomain: 'pratikumshinta.firebaseapp.com',
    storageBucket: 'pratikumshinta.firebasestorage.app',
    measurementId: 'G-LE0YDMC3PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfO78saFPgpOWuPytCHbWn4SlBssJ3esA',
    appId: '1:794780865383:android:6a83e94494ff2e6c5a15c2',
    messagingSenderId: '794780865383',
    projectId: 'pratikumshinta',
    storageBucket: 'pratikumshinta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAIP8nuo70W4-89BJss-l1uQEjTyUnvDI',
    appId: '1:794780865383:ios:e8769c8c3117818a5a15c2',
    messagingSenderId: '794780865383',
    projectId: 'pratikumshinta',
    storageBucket: 'pratikumshinta.firebasestorage.app',
    iosBundleId: 'com.example.shintaPraktikum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAIP8nuo70W4-89BJss-l1uQEjTyUnvDI',
    appId: '1:794780865383:ios:e8769c8c3117818a5a15c2',
    messagingSenderId: '794780865383',
    projectId: 'pratikumshinta',
    storageBucket: 'pratikumshinta.firebasestorage.app',
    iosBundleId: 'com.example.shintaPraktikum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkH_AwO0MH6CyMYGjaVZS19NrqlK2iDes',
    appId: '1:794780865383:web:84517535e3ce22405a15c2',
    messagingSenderId: '794780865383',
    projectId: 'pratikumshinta',
    authDomain: 'pratikumshinta.firebaseapp.com',
    storageBucket: 'pratikumshinta.firebasestorage.app',
    measurementId: 'G-NHL57V5KQL',
  );
}
